### ISSUE TITLE
out of boundaries exception thrown when using repair...

### ISSUE THREAD

**Issue by seninp** [GrammarViz2/grammarviz2_src#33]
psenin@piedras:~/git/grammarviz2_src.git$ java -cp "target/grammarviz2-0.0.1-SNAPSHOT-jar-with-dependencies.jar" net.seninp.grammarviz.GrammarVizAnomaly -d data/ecg0606_1.csv -alg RRA -w 120 -p 4 -a 4 -g REPAIR -n 3
GrammarViz2 CLI anomaly discovery
parameters:
 input file:                  data/ecg0606_1.csv
 output files prefix:         
 Algorithm implementation:    RRA
 Num. of discords to report:  3
 SAX sliding window size:     120
 SAX PAA size:                4
 SAX alphabet size:           4
 SAX numerosity reduction:    EXACT
 SAX normalization threshold: 0.01
 GI Algorithm:         Re-Pair

16:43:11.443 [main] INFO  n.s.grammarviz.GrammarVizAnomaly - Reading data ...
16:43:11.482 [main] INFO  n.s.grammarviz.GrammarVizAnomaly - read 2299 points from data/ecg0606_1.csv
16:43:11.482 [main] INFO  n.s.grammarviz.GrammarVizAnomaly - running RRA algorithm...
16:43:11.576 [main] INFO  n.s.grammarviz.GrammarVizAnomaly - Whole timeseries covered by rule intervals ...
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 2299
	at net.seninp.jmotif.sax.registry.VisitRegistry.isVisited(VisitRegistry.java:99)
	at net.seninp.grammarviz.anomaly.RRAImplementation.findBestDiscordForIntervals(RRAImplementation.java:153)
	at net.seninp.grammarviz.anomaly.RRAImplementation.series2RRAAnomalies(RRAImplementation.java:66)
	at net.seninp.grammarviz.GrammarVizAnomaly.findRRA(GrammarVizAnomaly.java:245)
	at net.seninp.grammarviz.GrammarVizAnomaly.main(GrammarVizAnomaly.java:149)

**Comment by seninp** [comment]
This sort of fixed by [SAX commit f374f6a00d9c04f532cdc763b8803fb07005b721](https://github.com/jMotif/SAX/commit/f374f6a00d9c04f532cdc763b8803fb07005b721)
