### ISSUE TITLE
Can't build on Windows 10 java 1.8 / maven 3.6

### ISSUE THREAD

**Issue by eusoubrasileiro** [GrammarViz2/grammarviz2_src#49]
I am trying to build directly from the cloned repository using the following:

`mvn package -Psingle`

I am on Windows 10 with the following maven and java: 

`java -version`
> java version "1.8.0_201"
> Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
> Java HotSpot(TM) Client VM (build 25.201-b09, mixed mode)

`mvn --version`

> Apache Maven 3.6.2 (40f52333136460af0dc0d7232c0dc0bcf0d9e117; 2019-08-27T12:06:16-03:00)
> Maven home: D:\Users\andre.ferreira\Projects\apache-maven-3.6.2\bin\..
> Java version: 13, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-13
> Default locale: pt_BR, platform encoding: Cp1252
> OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

I get the following errors:

```
INFO] Scanning for projects...
[INFO]
[INFO] -----------------------< net.seninp:grammarviz2 >-----------------------
[INFO] Building GrammarViz2 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- jacoco-maven-plugin:0.7.9:prepare-agent (default) @ grammarviz2 ---
[INFO] argLine set to -javaagent:D:\\Users\\andre.ferreira\\.m2\\repository\\org\\jacoco\\org.jacoco.agent\\0.7.9\\org.jacoco.agent-0.7.9-runtime.jar=destfile=D:\\Users\\andre.ferreira\\Projects\\grammarviz2_src-master\\target\\jacoco.exec,excludes=**/tinker/**:**/util/**:**/view/**:**/cli/**
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ grammarviz2 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory D:\Users\andre.ferreira\Projects\grammarviz2_src-master\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ grammarviz2 ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ grammarviz2 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory D:\Users\andre.ferreira\Projects\grammarviz2_src-master\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.3:testCompile (default-testCompile) @ grammarviz2 ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.13:test (default-test) @ grammarviz2 ---
[INFO] Surefire report directory: D:\Users\andre.ferreira\Projects\grammarviz2_src-master\target\surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
Caused by: java.lang.RuntimeException: Class java/util/UUID could not be instrumented.
        at org.jacoco.agent.rt.internal_8ff85ea.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:140)
        at org.jacoco.agent.rt.internal_8ff85ea.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:101)
        at org.jacoco.agent.rt.internal_8ff85ea.PreMain.createRuntime(PreMain.java:55)
        at org.jacoco.agent.rt.internal_8ff85ea.PreMain.premain(PreMain.java:47)
        ... 6 more
Caused by: java.lang.NoSuchFieldException: $jacocoAccess
        at java.base/java.lang.Class.getField(Class.java:2000)
        at org.jacoco.agent.rt.internal_8ff85ea.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:138)
        ... 9 more
*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at JPLISAgent.c line: 422
FATAL ERROR in native method: processing of -javaagent failed, processJavaStart failed

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.039 s
[INFO] Finished at: 2019-09-27T10:26:17-03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.13:test (default-test) on project grammarviz2: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.13:test failed: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ?
[ERROR] Command wascmd.exe /X /C ""C:\Program Files\Java\jdk-13\bin\java" -javaagent:D:\\Users\\andre.ferreira\\.m2\\repository\\org\\jacoco\\org.jacoco.agent\\0.7.9\\org.jacoco.agent-0.7.9-runtime.jar=destfile=D:\\Users\\andre.ferreira\\Projects\\grammarviz2_src-master\\target\\jacoco.exec,excludes=**/tinker/**:**/util/**:**/view/**:**/cli/** -Xms512m -Xmx1024m -jar D:\Users\andre.ferreira\Projects\grammarviz2_src-master\target\surefire\surefirebooter9849693331585176312.jar D:\Users\andre.ferreira\Projects\grammarviz2_src-master\target\surefire\surefire16016284318912983176tmp D:\Users\andre.ferreira\Projects\grammarviz2_src-master\target\surefire\surefire_017362929704599565515tmp"
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

**Comment by seninp** [comment]
Hello: I just checked the build on ubuntu, it is fine. I believe there are some windows-related issues with jacoco. Try to disable that plugin (in the build xml) and see if it succeeds. I'm not sure you'd need the code coverage data.

**Comment by vishrantgupta** [comment]
Setting `$JAVA_HOME` resolved the problem for me.

**Comment by jawadomari** [comment]
I have the same problem on Windows 10. I set the JAVA_HOME variable to the JDK folder, but with no luck. Any thoughts? Thanks.

**Comment by seninp** [comment]
Hi guys: I just tried and everything builds. I am really sorry for your experience, I hope the steps below will help you. If not, post your issues here, let's resolve:

```
C:\Users\psenin>systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
OS Name:                   Microsoft Windows 10 Home
OS Version:                10.0.18363 N/A Build 18363


[1] get the Java8
from https://www.oracle.com/java/technologies/javase/javase-jdk8-downloads.html

[2] Install Java setting ENV vars

C:\Users\psenin>SET
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\psenin\AppData\Roaming
ChocolateyInstall=C:\ProgramData\chocolatey
...
JAVA_HOME=c:\tools\java\jdk8
JDK_HOME=c:\tools\java\jdk8

C:\Users\psenin>java -version
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)

[3] install maven
from https://maven.apache.org/download.cgi?Preferred=ftp://ftp.osuosl.org/pub/apache/

C:\Users\psenin>SET
...
OS=Windows_NT
Path=C:\Program Files ... C:\tools\maven\apache-maven-3.6.3\bin;

C:\Users\psenin>mvn --version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\tools\maven\apache-maven-3.6.3\bin\..
Java version: 1.8.0_251, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jre1.8.0_251
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

[4] checkout the source code
$ pwd
/C/workspace

psenin@ps-rog MINGW64 /C/workspace
$ git clone https://github.com/GrammarViz2/grammarviz2_src.git
Cloning into 'grammarviz2_src'...
remote: Enumerating objects: 4275, done.
remote: Total 4275 (delta 0), reused 0 (delta 0), pack-reused 4275
Receiving objects: 100% (4275/4275), 25.64 MiB | 6.46 MiB/s, done.
Resolving deltas: 100% (2020/2020), done.

[5] build the package
c:\workspace\grammarviz2_src>mvn package -Psingle
[INFO] Scanning for projects...
[INFO]
[INFO] -----------------------< net.seninp:grammarviz2 >-----------------------
[INFO] Building GrammarViz2 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-assembly-plugin/2.5.4/maven-assembly-plugin-2.5.4.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-assembly-plugin/2.5.4/maven-assembly-plugin-2.5.4.pom (17 kB at 13 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-assembly-plugin/2.5.4/maven-assembly-plugin-2.5.4.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-assembly-plugin/2.5.4/maven-assembly-plugin-2.5.4.jar (238 kB at 489 kB/s)
[INFO]
[INFO] --- jacoco-maven-plugin:0.7.9:prepare-agent (default) @ grammarviz2 ---
[INFO] argLine set to -javaagent:C:\\Users\\psenin\\.m2\\repository\\org\\jacoco\\org.jacoco.agent\\0.7.9\\org.jacoco.agent-0.7.9-runtime.jar=destfile=c:\\workspace\\grammarviz2_src\\target\\jacoco.exec,excludes=**/tinker/**:**/util/**:**/view/**:**/cli/**
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ grammarviz2 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory c:\workspace\grammarviz2_src\src\main\resources
[INFO]
...
Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/3.0.21/plexus-utils-3.0.21.jar (245 kB at 175 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/commons-codec/commons-codec/1.6/commons-codec-1.6.jar (233 kB at 165 kB/s)
[INFO] Building jar: c:\workspace\grammarviz2_src\target\grammarviz2-0.0.1-SNAPSHOT-jar-with-dependencies.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  21.176 s
[INFO] Finished at: 2020-06-18T08:44:48+02:00
[INFO] ------------------------------------------------------------------------

[6] run the package 
c:\workspace\grammarviz2_src>java -Xmx8G -jar target/grammarviz2-0.0.1-SNAPSHOT-jar-with-dependencies.jar
Starting GrammarViz 3.0 ...
Changing runtime locale setting from en_US to en_US ...
[AWT-EventQueue-0] INFO GrammarVizView - 08:47:01 running GrammarViz 3.0 demo



```

**Comment by seninp** [comment]
here is the snap of running grammarviz [snap](https://imgur.com/a/P8dPgx7)

**Comment by jawadomari** [comment]
Thank you, it is running now. I previously had JRE and JDK installed at the same time.

**Comment by hrasto** [comment]
My setup was Apache Maven 3.5.4 and Java version: 1.8.0_202 on a mac, and I had to change the jacoco plugin to version 8.3 (8.2, as suggested in issue #50 didn't work either).
